Power measurement
ginkage/MHI-AC-Ctrl-ESPHome pull request #21
Opened 2022-05-25 10:04 UTC by GurtKnev

- using the current measurement and defining the voltage, we can create a rudimentary power measurement.

2022-06-14 21:20 UTC, Timple commented
I think with some magic in the yaml, that can be done.

One can even provide a rudimentary power meter: https://esphome.io/components/sensor/integration.html

Perhaps such an example can be added to the README yaml. In that case no additional code would be required.

2022-06-24 21:02 UTC, nbeernink commented
My setup is a multi-split (SCM50). I agree with @RoboMagus that this is probably better solved in Home Assistant itself. 

The two inner units that I have give the same "current power" rating even when only one unit has demand.  Merging this patch would add a sensor that would give an inaccurate power measurement for multi-splits.

My way of solving it is just adding a zigbee power plug with power measurement which connects the mhi multisplit to main power. I don't think it's possible to get an accurate reading per inner unit.

2022-07-18 19:27 UTC, RoboMagus requested changes

2024-03-22 10:32 UTC, RobertJansen1 commented
I think this is now already in from a different datasource, if not, can you please resubmit the patch?

2024-03-22 10:32 UTC, closed without merging